import type { Client, Session } from './types';

export const mockClients: Client[] = [
  {
    id: 'c1',
    name: '田中さん',
    ageLabel: '40代・女性',
    lastVisit: '2025-01-18',
    visitCount: 3,
  },
  {
    id: 'c2',
    name: '佐藤さん',
    ageLabel: '30代・女性',
    lastVisit: '2025-01-10',
    visitCount: 2,
  },
  {
    id: 'c3',
    name: '鈴木さん',
    ageLabel: '50代・男性',
    lastVisit: '2025-01-05',
    visitCount: 1,
  },
];

export const mockSessions: Session[] = [
  {
    id: 's1',
    clientId: 'c1',
    date: '2025-01-18',
    menu: '森の深眠スパ90分＋白髪カラー',
    visitNumber: 3,
    hrvBefore: 22,
    hrvAfter: 38,
    hrBefore: 76,
    hrAfter: 68,
    pre: {
      fatigue: 8,
      stiffness: 7,
      headHeaviness: 6,
      stress: 7,
      sleepQualityWeek: 4,
      sleepHoursLastNight: '5〜6時間',
      usualBedtime: '24〜1時',
      usualWakeTime: '6〜7時',
      lifestyleTags: ['smartphone', 'late_work'],
      lifestyleMemo: '寝る直前までスマホでSNSを見がち。',
      mainConcern: '寝つきが悪い',
    },
    post: {
      headLightness: 8,
      bodyRelax: 8,
      mentalRelax: 7,
      satisfaction: 5,
      comment: '肩と首がスッキリして、呼吸がしやすくなった。',
      actionNote: '寝る30分前にスマホをやめてストレッチをする。',
    },
  },
  {
    id: 's2',
    clientId: 'c1',
    date: '2024-12-28',
    menu: '森の深眠スパ60分',
    visitNumber: 2,
    hrvBefore: 20,
    hrvAfter: 32,
    hrBefore: 78,
    hrAfter: 70,
    pre: {
      fatigue: 7,
      stiffness: 6,
      headHeaviness: 5,
      stress: 6,
      sleepQualityWeek: 3,
      sleepHoursLastNight: '4〜5時間',
      usualBedtime: '24〜1時',
      usualWakeTime: '6〜7時',
      lifestyleTags: ['smartphone', 'late_caffeine'],
      lifestyleMemo: '',
      mainConcern: '夜中に何度も目が覚める',
    },
    post: {
      headLightness: 7,
      bodyRelax: 7,
      mentalRelax: 6,
      satisfaction: 4,
      comment: '前回よりも終わった後に眠気が出た感じ。',
      actionNote: '',
    },
  },
  {
    id: 's3',
    clientId: 'c2',
    date: '2025-01-10',
    menu: '森の深眠スパ90分',
    visitNumber: 2,
    hrvBefore: 18,
    hrvAfter: 30,
    hrBefore: 80,
    hrAfter: 72,
    pre: {
      fatigue: 6,
      stiffness: 5,
      headHeaviness: 4,
      stress: 6,
      sleepQualityWeek: 3,
      sleepHoursLastNight: '6〜7時間',
      usualBedtime: '22〜24時',
      usualWakeTime: '7〜8時',
      lifestyleTags: ['bath', 'stretch'],
      lifestyleMemo:
        'お風呂とストレッチはできているが、仕事の不安で入眠に時間がかかる。',
      mainConcern: '眠りが浅くて朝スッキリしない',
    },
    post: {
      headLightness: 8,
      bodyRelax: 9,
      mentalRelax: 8,
      satisfaction: 5,
      comment: '頭の奥の重さが軽くなった。',
      actionNote: '寝る前に呼吸を整える時間をつくりたい。',
    },
  },
];
